#
# Copyright 2013, Grid Dynamics Inc. Deming Project.
# @author Anton Haldin (ahaldin@griddynamics.com)
# @author Denis Khurtin (dkhurtin@griddynamics.com)
#

#################################
# Description of env properties #
#################################
header:
    services:
        properties:
            s3_bucket_name: consume-signal(string)

launch:
    parameters:
        cookbooks_url:
            description: "Cookbooks URL"
            default: "http://gd-bask.s3.amazonaws.com/cookbooks.tar.gz"
    steps:
        - get_env_props:
            action: getEnvironmentProperties
            parameters:
                phase: get-env-props
            output:
                config: result
        - start_build_server_vm:
            action: provisionVms
            phase: provision_build_server
            parameters:
                hardwareId: m1.medium
                imageId: us-east-1/ami-d41689bd
                vmIdentity: ec2-user
                roleName: build_server
                jcloudsNodeNamePrefix: build_server
            output:
                 build_server_ips: ips

        - build_server_setup:
            action: chefsolo
            phase: server_setup
            precedingPhases: [ provision_build_server ]
            parameters:
                roles: [ build_server ]
                runList: [ "recipe[java::openjdk]", "recipe[build-essential]", "recipe[s3manage::packages]" ]
                isSolo: true
                recipeUrl: ${cookbooks_url}
                jattrs:
                    java:
                        jdk_version: "7"
                        java_home: "/usr/lib/jvm/java/"

        - install_git:
            action: execrun
            phase: install_git
            precedingPhases: [ server_setup ]
            parameters:
                roles: [ build_server ]
                isSudo: true
                command:
                    - bash -c
                    - |
                        yum -y install git || exit 1

        - install_maven:
            action: execrun
            phase: install_maven
            precedingPhases: [ server_setup ]
            parameters:
                roles: [ build_server ]
                isSudo: true
                command:
                    - bash -c
                    - |
                        cd /usr/local || exit 1
                        wget "http://apache-mirror.rbc.ru/pub/apache/maven/maven-3/3.1.0/binaries/apache-maven-3.1.0-bin.tar.gz" || exit 2
                        tar -xzf apache-maven-3.1.0-bin.tar.gz || exit 3
                        echo 'export M2_HOME=/usr/local/apache-maven-3.1.0' > /etc/profile.d/maven.sh || exit 4
                        echo 'export M2=$$M2_HOME/bin' >> /etc/profile.d/maven.sh || exit 5
                        echo 'export PATH=$$M2:$$PATH' >> /etc/profile.d/maven.sh || exit 6
                        source /etc/profile.d/maven.sh || exit 7
                        ln -s /usr/local/apache-maven-3.1.0/bin/mvn /usr/bin/mvn || exit 8
                        mvn -version || exit 9

    return:
        build_server_ip:
            description: "Build Server IP:"
            value: "{$.build_server_ips[0]}"


Redeploy_java_artifacts:
    parameters:
        git_repo_url:
            description: "Git repo URL"
            default: "https://github.com/griddynamics/Behavior-Analytic-Starter-Kit.git"
        repo_localpath:
            description: "Local path to repo"
            default: "/var/local/git_repos/bask"
        repo_branch:
            description: "Git branch"
            default: "master"
    steps:
        - clone_git_repo:
            action: execrun
            phase: clone_repository
            parameters:
                roles: [ build_server ]
                isSudo: true
                command:
                    - bash -c
                    - |
                        if [ -d ${repo_localpath} ]; then
                            cd ${repo_localpath} || exit -1
                            git fetch --all || exit -2
                        else
                            git clone ${git_repo_url} ${repo_localpath} || exit 1
                            cd ${repo_localpath} || exit 2
                        fi
                        git reset --hard origin/${repo_branch} || exit 3

        - build_maven_projects:
            action: execrun
            phase: build_maven_projects
            precedingPhases: [ clone_repository ]
            parameters:
                roles: [ build_server ]
                isSudo: true
                command:
                    - bash -c
                    - |
                        cd ${repo_localpath}/maven_projects || exit 1
                        mvn clean install || exit 2
                        [ ! -d "${repo_localpath}/maven_artifacts" ] && rm -rf ${repo_localpath}/maven_artifacts || exit 3
                        mkdir "${repo_localpath}/maven_artifacts" || exit 4
                        cp ${repo_localpath}/maven_projects/web-store/site/target/site.war \
                           ${repo_localpath}/maven_artifacts/webstore.war || exit 5
                        cp ${repo_localpath}/maven_projects/web-store/admin/target/admin.war \
                           ${repo_localpath}/maven_artifacts/webstore-admin.war || exit 6
                        cp ${repo_localpath}/maven_projects/dataset-generator/target/dataset-generator-1.0-SNAPSHOT-jar-with-dependencies.jar \
                           ${repo_localpath}/maven_artifacts/transaction-log-generator.jar || exit 7
                        cp ${repo_localpath}/maven_projects/recommendation-processor/target/recommendation-processor-1.0-SNAPSHOT-jar-with-dependencies.jar \
                           ${repo_localpath}/maven_artifacts/recommendation-processor.jar || exit 8

        - uploading_webstore_to_S3:
            action: .s3manage
            phase: uploading_webstore_to_S3
            precedingPhases: [ build_maven_projects ]
            parameters:
                localpath: "${repo_localpath}/maven_artifacts/webstore.war"
                bucket: "{$.config.properties.s3_bucket_name}"
                action: "upload"

        - uploading_webstore_admin_to_S3:
            action: .s3manage
            phase: uploading_webstore_admin_to_S3
            precedingPhases: [ build_maven_projects ]
            parameters:
                localpath: "${repo_localpath}/maven_artifacts/webstore-admin.war"
                bucket: "{$.config.properties.s3_bucket_name}"
                action: "upload"

        - uploading_transaction_log_generator_to_S3:
            action: .s3manage
            phase: uploading_transaction_log_generator_to_S3
            precedingPhases: [ build_maven_projects ]
            parameters:
                localpath: "${repo_localpath}/maven_artifacts/transaction-log-generator.jar"
                bucket: "{$.config.properties.s3_bucket_name}"
                action: "upload"

        - uploading_recommendation_processor_to_S3:
            action: .s3manage
            phase: uploading_recommendation_processor_to_S3
            precedingPhases: [ build_maven_projects ]
            parameters:
                localpath: "${repo_localpath}/maven_artifacts/recommendation-processor.jar"
                bucket: "{$.config.properties.s3_bucket_name}"
                action: "upload"


####################
# Hidden workflows #
####################
.s3manage:
    parameters:
        aws_access_key_id:
            description: "aws_access_key_id"
        aws_secret_access_key:
            description: "aws_secret_access_key"
        localpath:
            description: "local file path"
        bucket:
            description: "s3 bucket"
        s3file:
            description: "s3 file name (only for download)"
            default: ""
        action:
            description: "file action"
    steps:
        s3transfer:
            action: chefsolo
            phase: transferring
            parameters:
                roles: [ build_server ]
                runList: [ "recipe[s3manage::default]" ]
                isSolo: true
                recipeUrl: "http://gd-bask.s3.amazonaws.com/cookbooks.tar.gz"
                jattrs:
                    s3manage:
                        access_key_id: ${aws_access_key_id}
                        secret_access_key: ${aws_secret_access_key}
                        localpath: ${localpath}
                        bucket: ${bucket}
                        s3file: ${s3file}
                        action: ${action}


destroy:
    steps:
        - destroy:
            action: undeployEnv
            phase: destroy
